### ISSUE TITLE
Tasting Geta (version 17July)

### ISSUE THREAD

**Issue by vitagrazia81** [TraCES-Lexicon/GeTa#2]
Small "problem" which occours when you want to correct a Preposition into a Conjunction, that is the following.
You open the window "Linguistic Annotation" for the Preposition which you want to correct. Then, you change the PoS selecting the new one. After  having selected the PoS Conjunction you see that the sub/internal window of "Deep Annotation" (where before the features for the preposition were displayed) becomes empty (as it should be). Then, you click the bottom "Annotate" and the main window of "Linguistic Annotation" gets closed. Afterwards, only if you check the upper window "show corrent word annotation", for the updated annotion you realize that there is a mistake: you read  rightly that is now a Conjuction but wrongly that has the State (Nominal or Pronominal) as for the preposition. Then, to correct, you have to open again the window of "Linguistic Annotation ("Modify")" and you see that the PoS is correct but in the "Deep Annotation" window the "state" appears. To deselect this information, it is needed to open the window "deep annotation" and to click "Assign" and after the bottom "Annotate".

**Comment by cvertan** [comment]
This was a more general issue; it was in fact valid whenever you change completely the PoS. Solved
